iut/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('management.urls')),
]

management/urls.py
from django.urls import path

from management.views import home, planning, promotion, semester, session, subject, td, teacher, tp, week, year, cost, \
    csv, settings

app_name = 'management'
urlpatterns = [
    path('settings/exporting-csv', csv.exporting_csv, name='exporting-csv'),
    path('settings/import-csv', csv.import_csv, name='import-csv'),
    path('settings', settings.managed_settings, name='managed-settings'),
    path('settings/edit/cost', settings.edit_cost_settings, name='edit-cost-settings'),

    path('', home.index, name='index'),
    path('accounts/login/', home.user_login, name='login'),
    path('accounts/logout/', home.user_logout, name='logout'),
    path('accounts/change/password/<int:teacher_id>', home.user_change_password, name='change-password'),

    path('add/year', year.add_year, name="add-year"),
    path('add/teacher', teacher.add_teacher, name="add-teacher"),
    path('add/promotion', promotion.add_promotion, name="add-promotion"),

    path('managed/promotion/<int:promotion_id>', promotion.managed_promotion, name="managed-promotion"),
    path('managed/promotion/<int:promotion_id>/add/td', td.add_td, name="add-td"),
    path('managed/promotion/<int:promotion_id>/managed/td/<int:td_id>', td.managed_td, name="managed-td"),
    path('managed/promotion/<int:promotion_id>/managed/td/<int:td_id>/add/tp', tp.add_tp, name="add-tp"),
    path('managed/promotion/<int:promotion_id>/add/subject', subject.add_subject, name="add-subject"),
    path('managed/promotion/<int:promotion_id>/edit/subject/<int:subject_id>', subject.edit_subject,
         name="edit-subject"),
    path('managed/promotion/<int:promotion_id>/managed/subject/<int:subject_id>', subject.managed_subject,
         name="managed-subject"),
    path('managed/promotion/<int:promotion_id>/managed/subject/<int:subject_id>/add/session/cm', session.add_cm_session,
         name="add-cm-session"),
    path('managed/promotion/<int:promotion_id>/managed/subject/<int:subject_id>/add/session/td', session.add_td_session,
         name="add-td-session"),
    path('managed/promotion/<int:promotion_id>/managed/subject/<int:subject_id>/add/session/tp', session.add_tp_session,
         name="add-tp-session"),
    path('managed/promotion/<int:promotion_id>/managed/subject/<int:subject_id>/edit/session/<int:session_id>',
         session.edit_session, name="edit-session"),

    path('managed/year/<int:year_id>', year.managed_year, name="managed-year"),
    path('managed/year/<int:year_id>/add/semester', semester.add_semester, name="add-semester"),
    path('managed/year/<int:year_id>/managed/semester/<int:semester_id>', semester.managed_semester,
         name="managed-semester"),
    path('managed/year/<int:year_id>/managed/semester/<int:semester_id>/add/week', week.add_week, name="add-week"),
    path('managed/year/<int:year_id>/managed/semester/<int:semester_id>/add/nextweek', week.add_next_week,
         name="add-next-week"),
    path('managed/year/<int:year_id>/managed/semester/<int:semester_id>/add/duplicateweek/<int:week_id>',
         week.duplicate_next_week, name="add-duplicate-week"),
    path('managed/year/<int:year_id>/managed/planning', planning.managed_planning, name='managed-planning'),
    path('managed/year/<int:year_id>/add/planning/<int:sessions_id>', planning.add_planning, name='add-planning'),
    path('managed/year/<int:year_id>/managed/semester/<int:semester_id>/planning/week/<int:week_id>',
         planning.managed_week_planning, name="managed-week-planning"),
    path('managed/year/<int:year_id>/managed/semester/<int:semester_id>/planning/week/<int:week_id>/add/planning/<int'
         ':sessions_id>', planning.add_week_planning, name='add-week-planning'),
    path('managed/year/<int:year_id>/managed/cost', cost.managed_cost, name='managed-cost'),

    path('managed/teacher/<int:teacher_id>', teacher.managed_teacher, name='managed-teacher'),
    path('edit/teacher/<int:teacher_id>', teacher.edit_teacher, name='edit-teacher'),

    path('delete/year/<int:year_id>', year.delete_year, name='delete-year'),
    path('managed/year/<int:year_id>/delete/semester/<int:semester_id>', semester.delete_semester,
         name='delete-semester'),
    path('managed/year/<int:year_id>/managed/semester/<int:semester_id>/delete/week<int:week_id>', week.delete_week,
         name="delete-week"),

    path('delete/teacher/<int:teacher_id>', teacher.delete_teacher, name='delete-teacher'),

    path('delete/promotion/<int:promotion_id>', promotion.delete_promotion, name="delete-promotion"),
    path('managed/promotion/<int:promotion_id>/delete/td/<int:td_id>', td.delete_td, name="delete-td"),
    path('managed/promotion/<int:promotion_id>/managed/td/<int:td_id>/delete/tp/<int:tp_id>', tp.delete_tp,
         name="delete-tp"),
    path('managed/promotion/<int:promotion_id>/delete/subject/<int:subject_id>', subject.delete_subject,
         name="delete-subject"),
    path('managed/promotion/<int:promotion_id>/managed/subject/<int:subject_id>/delete/session/<int:session_id>',
         session.delete_session, name="delete-session"),

    path('managed/year/<int:year_id>/delete/planning/<int:planning_id>', planning.delete_planning,
         name='delete-planning'),
]

management/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class Year(models.Model):
    name_year = models.CharField(max_length=20)

    def __str__(self):
        return self.name_year


class Semester(models.Model):
    name_semester = models.CharField(max_length=20)
    year = models.ForeignKey(Year, on_delete=models.CASCADE)

    def __str__(self):
        return self.name_semester


class Week(models.Model):
    name_week = models.DateField()
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name_week)


class Teacher(AbstractUser):
    StatusChoices = models.TextChoices('type', 'professeur vacataire')
    status = models.CharField(blank=True, choices=StatusChoices.choices, max_length=20)


class Promotion(models.Model):
    name_promotion = models.CharField(max_length=20)
    year = models.ForeignKey(Year, on_delete=models.CASCADE)

    def __str__(self):
        return self.name_promotion


class Td(models.Model):
    name_td = models.CharField(max_length=5)
    promotion = models.ForeignKey(Promotion, on_delete=models.CASCADE)
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE)

    def __str__(self):
        return self.name_td


class Tp(models.Model):
    name_tp = models.CharField(max_length=5)
    td = models.ForeignKey(Td, on_delete=models.CASCADE)

    def __str__(self):
        return self.name_tp


class Subject(models.Model):
    name_subject = models.CharField(max_length=20)
    description = models.CharField(max_length=120)
    number_cm_sessions = models.FloatField(default=0)
    number_td_sessions = models.FloatField(default=0)
    number_tp_sessions = models.FloatField(default=0)
    promotion = models.ForeignKey(Promotion, on_delete=models.CASCADE)
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE)

    def __str__(self):
        return self.name_subject


class Sessions(models.Model):
    TypeSessionsChoices = models.TextChoices('type', 'cm td tp')
    type_sessions = models.CharField(blank=True, choices=TypeSessionsChoices.choices, max_length=20)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    number_hours = models.FloatField(default=0)
    promotion = models.ForeignKey(Promotion, blank=True, null=True, on_delete=models.CASCADE, related_name='promotion')
    td = models.ForeignKey(Td, blank=True, null=True, on_delete=models.CASCADE, related_name='td')
    tp = models.ForeignKey(Tp, blank=True, null=True, on_delete=models.CASCADE, related_name='tp')
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)


class Planning(models.Model):
    sessions = models.ForeignKey(Sessions, on_delete=models.CASCADE)
    number_hours = models.FloatField(default=0)
    week = models.ForeignKey(Week, on_delete=models.CASCADE)

management/views/cost.py
import json

from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render

from management.models import Sessions, Teacher, Subject, Semester, Year


@login_required
@user_passes_test(lambda u: u.is_superuser)
def managed_cost(request, year_id):
    teacher = Teacher.objects.all()
    year = Year.objects.get(pk=year_id)

    file = open('settings.json')
    settings = json.load(file)

    cost_teacher = {}

    for one_teacher in teacher:
        cost_teacher[one_teacher.last_name] = {"cost": 0.0, "cm": 0.0, "td": 0.0, "tp": 0.0}

        for one_session in Sessions.objects.filter(teacher=one_teacher, promotion__year=year_id).all():
            cost_teacher[one_teacher.last_name][one_session.type_sessions] += float(one_session.number_hours)
            cost_teacher[one_teacher.last_name]["cost"] += ((settings[one_teacher.status]["hour_price"] *
                                                             settings[one_teacher.status]["eq_td"][
                                                                 one_session.type_sessions]) * one_session.number_hours)

    cost_subject = {}

    for one_subject in Subject.objects.filter(promotion__year=year_id):
        cost_subject[one_subject.name_subject] = {"cost": 0.0, "cm": 0.0, "td": 0.0, "tp": 0.0}

        for one_session in Sessions.objects.filter(subject=one_subject).all():
            cost_subject[one_subject.name_subject][one_session.type_sessions] += float(one_session.number_hours)
            cost_subject[one_subject.name_subject]["cost"] += ((settings[one_session.teacher.status]["hour_price"] *
                                                                settings[one_session.teacher.status]["eq_td"][
                                                                    one_session.type_sessions]) * one_session.number_hours)

    cost_semester = {}

    for one_semester in Semester.objects.filter(year=year_id):
        cost_semester[one_semester.name_semester] = {"cost": 0.0, "cm": 0.0, "td": 0.0, "tp": 0.0}

        for one_session in Sessions.objects.filter(subject__semester=one_semester).all():
            cost_semester[one_semester.name_semester][one_session.type_sessions] += float(one_session.number_hours)
            cost_semester[one_semester.name_semester]["cost"] += ((settings[one_session.teacher.status]["hour_price"] *
                                                                   settings[one_session.teacher.status]["eq_td"][
                                                                       one_session.type_sessions]) * one_session.number_hours)

    return render(request, 'management/cost.html',
                  {'year': year, "cost_teacher": cost_teacher, "cost_subject": cost_subject,
                   "cost_semester": cost_semester})

management/views/home.py
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from management.forms import Login, ChangePassword
from management.models import Promotion, Teacher, Year


@login_required
def index(request):
    """
    Récupère les années, les professeurs et les promotions pour les envoyer à la vue.
    """
    year = Year.objects.all().order_by("-name_year")
    teacher = Teacher.objects.all().order_by("last_name")
    promotion = Promotion.objects.all().order_by("-year__name_year")

    return render(request, 'management/index.html',
                  {'year': year, 'teacher': teacher, 'promotion': promotion, 'current_session': request.user})


def user_login(request):
    if request.method == 'POST':
        form = Login(request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(request.GET['next'])
            else:
                return render(request, 'management/login.html',
                              {'form': form, 'error': 'Utilisateur et/ou les mots de pass et incorrect',
                               'next_url': request.GET['next']})
    else:
        form = Login()
        return render(request, 'management/login.html', {'form': form, 'next_url': request.GET['next']})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('management:index'))


@login_required
def user_change_password(request, teacher_id):
    post_url = reverse('management:change-password', args=(teacher_id,))
    back_url = reverse('management:index')

    if request.method == 'POST':
        form = ChangePassword(request.POST)
        if form.is_valid():
            user = Teacher.objects.get(pk=teacher_id)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return HttpResponseRedirect(reverse('management:index'))
    else:
        form = ChangePassword()
        return render(request, 'management/edit-form.html', {'form': form, "post_url": post_url, "back_url": back_url,
                                                             'info': "Le changement de mots de passe déconnectera "
                                                                     "l'utilisateur de toutes ses sessions !"})

management/views/promotion.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from management.forms import AddPromotion, DeleteForm
from management.models import Promotion


@login_required
@user_passes_test(lambda u: u.is_superuser)
def add_promotion(request):
    """
    Fiche la vue responsable de l'ajout d'une promotions et gère le retour de celle-ci.
    """
    post_url = reverse('management:add-promotion', args=())
    back_url = reverse('management:index', args=())

    if request.method == 'POST':
        form = AddPromotion(request.POST)
        if form.is_valid():
            '''
            Si le formulaire a été soumi, on vérifie que les champs ont été correctement remplis.
            '''

            if len(Promotion.objects.filter(name_promotion=form.cleaned_data['name_promotion']).all()):
                '''
                Si la promotions existe déjà on revoie le formulaire avec une erreur.
                '''

                return render(request, 'management/add-form.html',
                              {'form': form, 'error': 'La promotion existe déjà', 'post_url': post_url,
                               "back_url": back_url})

            '''
            Ajoute les données à la BDD et redirige le client.
            '''

            new_promotion = Promotion(name_promotion=form.cleaned_data['name_promotion'],
                                      year=form.cleaned_data['year'])
            new_promotion.save()
            return HttpResponseRedirect(reverse('management:managed-promotion', args=(new_promotion.id,)))
    else:
        '''
        Sinon on affiche le formulaire vide.
        '''

        form = AddPromotion()
        return render(request, 'management/add-form.html', {'form': form, 'post_url': post_url, "back_url": back_url})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def managed_promotion(request, promotion_id):
    """
    Affiche la vue qui rassemble toutes les données sur une promotion.
    """

    promotion = Promotion.objects.get(pk=promotion_id)
    td = promotion.td_set.all()
    subject = promotion.subject_set.all().order_by("name_subject")
    return render(request, 'management/managed-promotion.html', {'promotion': promotion, 'td': td, 'subject': subject})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def delete_promotion(request, promotion_id):
    post_url = reverse('management:delete-promotion', args=(promotion_id,))
    back_url = reverse('management:index', args=())

    if request.method == 'POST':
        form = DeleteForm(request.POST)
        if form.is_valid():
            if not form.cleaned_data['confirm']:
                return render(request, 'management/delete-form.html',
                              {'form': form, 'error': 'Vous devez confirmer la suppression', 'post_url': post_url,
                               "back_url": back_url})

            promotion = Promotion.objects.get(pk=promotion_id)
            promotion.delete()
            return HttpResponseRedirect(reverse('management:index', args=()))
    else:
        form = DeleteForm()
        return render(request, 'management/delete-form.html',
                      {'form': form, 'post_url': post_url, "back_url": back_url,
                       "info": "Tous les éléments liés à cette promotion seront aussi supprimés !"})

management/templates/management/add-week.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ADD</title>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>

    <!-- Fengyuan Chen's Datepicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css"
          integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous"/>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js"
            integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'management/add-form.css' %}"/>
</head>
<body>
<form action="{% url 'management:add-week' year_id semester_id %}" method="post">
    {% csrf_token %}

    <script>
        $(function () {
            $("#id_name_week").datepicker({
                language: "fr-FR",
                weekStart: 1
            });
        });
    </script>
    <!---->
    {% if error %}
        <div class="error">
            <p>{{ error }}</p>
        </div>
    {% endif %}
    <!---->
    <div class="inputs">{{ form }}</div>
    <input type="submit" value="Ajouter"/>
    <a href="{% url 'management:managed-semester' year_id semester_id %}"><p>Annuler</p></a>
</form>
</body>
</html>

management/templates/management/edit-planning.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'management/edit-planning.css' %}" />

<div class="title">
  <h1>Planification</h1>
  <p>{{ year }}</p>
  <a class="btn-back" href="{% url 'management:edit-year' year.id %}">← back</a>
</div>

<div class="container">
  <div class="year">
    <div class="info">
      <p>Séance affecter aux semaines</p>
    </div>
    {% for one_semester in year.semester_set.all %}
    <table>
      <tr>
        <th colspan="5">{{ one_semester }}</th>
      </tr>
      <tr>
        <th>Matiere</th>
        <th>Promotion</th>
        <th>Semaine</th>
        <th>Nombre de séances</th>
        <th>Professeur</th>
      </tr>
      {% for one_week in one_semester.week_set.all %} {% for one_planning in one_week.planning_set.all %}
      <tr>
        <td>{{ one_planning.sessions.subject }}</td>
        <td>{{ one_planning.sessions.promotion }}</td>
        <td>{{ one_week }}</td>
        <td>{{ one_planning.number_sessions }}</td>
        <td>{{ one_planning.sessions.teacher }}</td>
      </tr>
      {% endfor %} {% endfor %}
    </table>

    {% endfor %}
  </div>

  <br />

  <div class="padding">
    <div class="info">
      <p>Séance à affecter à une semaine</p>
    </div>
    <table>
      <tr>
        <th>Matiere</th>
        <th>Promotion</th>
        <th>Type de séance</th>
        <th>Nombre de séance</th>
        <th>Professeur</th>
        <th>Affecter</th>
      </tr>
      {% for remaining_session_id, remaining_session_data in remaining_session.items %} {% if remaining_session_data.number_sessions > 0 %}
      <tr>
        <td>{{ remaining_session_data.name_subject }}</td>
        <td>{{ remaining_session_data.promotion }}</td>
        <td>{{ remaining_session_data.type_sessions }}</td>
        <td>{{ remaining_session_data.number_sessions }}</td>
        <td>{{ remaining_session_data.teacher }}</td>
        <td><a class="btn-back" href="{% url 'management:add-planning' year.id remaining_session_id %}">+</a></td>
      </tr>
      {% endif %} {% endfor %}
    </table>
  </div>
</div>

management/templates/management/edit-semester.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'management/edit-semester.css' %}" />

<div class="title">
  <h1>{{ semester.name_semester }}</h1>
  <p>{{ year.name_year }}</p>
  <a class="btn-back" href="{% url 'management:edit-year' year.id%}">← back</a>
</div>

<div class="container">
  <div class="week">
    <h2>Semestre</h2>
    <div class="list">
      {% for one_week in semester.week_set.all %}
      <div class="item">
        <p>{{ one_week }}</p>
      </div>
      {% endfor %}
    </div>
    <a class="btn-add" href="{% url 'management:add-week' year.id semester.id %}">Ajouter un semaine</a>
  </div>
</div>

management/templates/management/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" type="text/css" href="{% static 'management/index.css' %}"/>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"/>
</head>
<body>
<div class="title">
    <h1>IUT Calais</h1>
    <p>GDS | Beta : v0.1</p>
    <a class="btn-back" href="{% url 'management:logout' %}">
        <span class="material-symbols-outlined">logout</span>
    </a>
    {% if current_session.is_superuser %}
        <a class="btn-back" href="{% url 'management:managed-settings' %}">
        <span class="material-symbols-outlined">
            settings
        </span>
        </a>
    {% endif %}
</div>
<div class="container">
    {% if current_session.is_superuser %}
        <div class="year">
            <h2>Année</h2>
            <div class="list">
                {% for one_year in year %}
                    <div class="item">
                        <p>{{ one_year }}</p>
                        <div class="btn">
                            <a href="{% url 'management:managed-year' one_year.id %}">Géré</a>
                            <a href="{% url 'management:delete-year' one_year.id %}">Supprimer</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <a class="btn-add" href="{% url 'management:add-year' %}">Ajouter une année</a>
        </div>
    {% endif %}

    <div class="teacher">
        <h2>Professeur</h2>
        <div class="list">
            {% for one_teacher in teacher %}
                {% if current_session.is_superuser or current_session.id == one_teacher.id %}
                    <div class="item">
                        <p>{{ one_teacher }}</p>
                        <div class="btn">
                            <a href="{% url 'management:managed-teacher' one_teacher.id %}">Voir service</a>
                            {% if current_session.is_superuser %}
                                <a href="{% url 'management:edit-teacher' one_teacher.id %}">Géré</a>
                                <a href="{% url 'management:delete-teacher' one_teacher.id %}">Supprimer</a>
                            {% endif %}
                            <a href="{% url 'management:change-password' one_teacher.id %}">Changer le mot de passe</a>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        {% if current_session.is_superuser %}
            <a class="btn-add" href="{% url 'management:add-teacher' %}"><p>Ajouter un professeur</p></a>
        {% endif %}
    </div>

    {% if current_session.is_superuser %}
        <div class="promotion">
            <h2>Promotion</h2>
            <div class="list">
                {% for one_promotion in promotion %}
                    <div class="item">
                        <p>{{ one_promotion }}</p>
                        <div class="btn">
                            <a href="{% url 'management:managed-promotion' one_promotion.id %}">Géré</a>
                            <a href="{% url 'management:delete-promotion' one_promotion.id %}">Supprimer</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <a class="btn-add" href="{% url 'management:add-promotion' %}"><p>Ajouter une promotion</p></a>
        </div>
    {% endif %}
</div>
</body>
</html>

management/templates/management/managed-semester.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Semester</title>
    <link rel="stylesheet" type="text/css" href="{% static 'management/managed-semester.css' %}"/>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"/>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"/>
</head>
<body>
<div class="title">
    <h1>{{ semester.name_semester }}</h1>
    <p>{{ year.name_year }}</p>
    <a class="btn-back" href="{% url 'management:managed-year' year.id %}">
        <span class="material-symbols-outlined">arrow_back</span>
    </a>
    <a class="btn-back" href="{% url 'management:index' %}"><span class="material-symbols-outlined">home</span></a>
</div>

<div class="container">
    <div class="week">
        <h2>Semestre</h2>
        <div class="list">
            {% for one_week in semester.week_set.all %}
                <div class="item">
                    <p>{{ one_week }}</p>
                    <div class="btn">
                        <a href="{% url 'management:managed-week-planning' year.id semester.id one_week.id %}">Modifier
                            la planification</a>
                        <a href="{% url 'management:add-duplicate-week' year.id semester.id one_week.id %}">Dupliquer</a>
                        <a href="{% url 'management:delete-week' year.id semester.id one_week.id %}">Supprimer</a>
                    </div>
                </div>
            {% endfor %}
            {% if semester.week_set.all %}
                <div class="item">
                    <p>Semaine suivante</p>
                    <div class="btn">
                        <a href="{% url 'management:add-next-week' year.id semester.id %}">Ajouter la semaine</a>
                    </div>
                </div>
            {% endif %}
        </div>
        <a class="btn-add" href="{% url 'management:add-week' year.id semester.id %}">Ajouter une semaine</a>
    </div>
</div>
</body>
</html>

management/templates/management/managed-year.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Year</title>
    <link rel="stylesheet" type="text/css" href="{% static 'management/managed-year.css' %}"/>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"/>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"/>
</head>
<body>
<div class="title">
    <h1>{{ year.name_year }}</h1>
    <a class="btn-back" href="{% url 'management:index' %}">
        <span class="material-symbols-outlined">arrow_back</span>
    </a>
    <a class="btn-back" href="{% url 'management:index' %}"><span class="material-symbols-outlined">home</span></a>
</div>

<div class="container">
    <div class="semester">
        <h2>Semestre</h2>
        <div class="list">
            {% for one_semester in year.semester_set.all %}
                <div class="item">
                    <h3>{{ one_semester }}</h3>
                    <div class="weeks">
                        {% for one_week in one_semester.week_set.all %}
                            <div class="week">
                                <p>{{ one_week }}</p>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="btn">
                        <a href="{% url 'management:managed-semester' year.id one_semester.id %}">Géré</a>
                        <a href="{% url 'management:delete-semester' year.id one_semester.id %}">Supprimer</a>
                    </div>
                </div>
            {% endfor %}
        </div>
        <a class="btn-add" href="{% url 'management:add-semester' year.id %}">Ajouter un semestre</a>
        <a class="btn-add" href="{% url 'management:managed-planning' year.id %}">Modifier la planification</a>
        <a class="btn-add" href="{% url 'management:managed-cost' year.id %}">Voir les coûts</a>
    </div>
</div>